### ISSUE TITLE
Extensions testing against Solidus versions that have reached EOL

### ISSUE THREAD

**Issue by jacobherrington** [solidusio/solidus#2866]
I would like to get some discussion on this:

I recently added a new Solidus versions to TravisCI in bunch of Solidus extensions. I noticed that some extensions have .travis.yml files that list a ton of Solidus versions which have now reach EOL. 

(from [solidus_i18n](https://github.com/solidusio/solidus_i18n))
```yml
dist: trusty
sudo: required
addons:
  chrome: stable
cache: bundler
language: ruby
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978
  - gem install bundler
rvm:
  - 2.5
env:
  matrix:
    - SOLIDUS_BRANCH=v1.1 DB=postgres
    - SOLIDUS_BRANCH=v1.2 DB=postgres
    - SOLIDUS_BRANCH=v1.3 DB=postgres
    - SOLIDUS_BRANCH=v1.4 DB=postgres
    - SOLIDUS_BRANCH=v2.0 DB=postgres
    - SOLIDUS_BRANCH=v2.1 DB=postgres
    - SOLIDUS_BRANCH=v2.2 DB=postgres
    - SOLIDUS_BRANCH=v2.3 DB=postgres
    - SOLIDUS_BRANCH=v2.4 DB=postgres
    - SOLIDUS_BRANCH=v2.5 DB=postgres
    - SOLIDUS_BRANCH=v2.6 DB=postgres
    - SOLIDUS_BRANCH=v2.7 DB=postgres
    - SOLIDUS_BRANCH=master DB=postgres
    - SOLIDUS_BRANCH=v1.1 DB=mysql
    - SOLIDUS_BRANCH=v1.2 DB=mysql
    - SOLIDUS_BRANCH=v1.3 DB=mysql
    - SOLIDUS_BRANCH=v1.4 DB=mysql
    - SOLIDUS_BRANCH=v2.0 DB=mysql
    - SOLIDUS_BRANCH=v2.1 DB=mysql
    - SOLIDUS_BRANCH=v2.2 DB=mysql
    - SOLIDUS_BRANCH=v2.3 DB=mysql
    - SOLIDUS_BRANCH=v2.4 DB=mysql
    - SOLIDUS_BRANCH=v2.5 DB=mysql
    - SOLIDUS_BRANCH=v2.6 DB=mysql
    - SOLIDUS_BRANCH=v2.7 DB=mysql
    - SOLIDUS_BRANCH=master DB=mysql
```

This kind of thing causes tests to take a lot longer, and in some cases [when CI hangs](https://travis-ci.org/solidusio-contrib/solidus_subscriptions/builds/432445845?utm_source=github_status&utm_medium=notification), tests can take a really long time.

Should we only be testing extensions against [versions that haven't reached EOL](https://solidus.io/blog/2018/01/04/maintenance-eol-policy.html)?
