### ISSUE TITLE
New admin components i18n scope too granular

### ISSUE THREAD

**Issue by tvdeyen** [solidusio/solidus#6242]
### Discussed in https://github.com/orgs/solidusio/discussions/6222

<div type='discussions-op-text'>

<sup>Originally posted by **nerijunior** April 22, 2025</sup>
Hi, first time using Solidus, and the new UI looks amazing, but I'm facing some issues translating that.

Looking at the `solidus_admin` implementation, every component loads its own `.yml` file and uses the strings related to the parent-child relation, e.g:

The component `SolidusAdmin::Users::Edit::Component` will generate the user/edit screen that will generate some tabs and use the tabs strings from `app/components/solidus_admin/users/edit/component.yml`, inside the Ruby code it's calling something like `t('.account'),`, so I need to have a structure like that at the yml file

```
en:
  solidus_admin:
    users:
      edit:
        account: ...
```

The problem is that inside `users/edit` we have 5 tabs, and when I go to another tab, it should reuse the same strings, but to have all pages translated, I need to duplicate all the tabs strings to the 5 tabs like this:

```
en:
  solidus_admin:
    users:
      edit:
        account: ...
      addresses:
        account: ...
      orders:
        account: ...
```

Is there a better way to do that?

I tried to use `solidus_i18n`, but I think it's not updated regarding the new admin UI.</div>
